site_name: FOX - A LINK TO THE PRICE
site_description: Documentação para uso do robô para Telegram Fox - A Link to the Price
site_author: Samir Angelo Milani Martins
site_url: https://www.samirmartins.com.br

copyright: Copyright &copy; 2023 - Samir Martins

nav:
  - Principal: index.md
  - Commandos Básicos:
    - /ajuda: ajuda.md
    - /ativosdisponiveis: ativosdisponiveis.md
    - /escrevame: escrevame.md
    - /contatos: contatos.md
    - /videotutorial: videotutorial.md
    - /documentacao: documentacao.md
  - Análise Técnica:
    - /resumo: resumo.md
    - /barradesinal: barradesinal.md
    - /tamanhobarras: tamanhobarras.md
    - /tendencia: tendencia.md
    - /localizacao: localizacao.md
    - /canal: canal.md
    - /tipodemercado: tipodemercado.md
    - /rompimentos: rompimentos.md
    - /rsi: rsi.md
    - /stochrsi: stochrsi.md
    - /stoch: stoch.md
    - /tsi: tsi.md
    - /ao: ao.md
    - /ppo: ppo.md
    - /roc: roc.md
    - /correlacao: correlacao.md
  - Análise Fundamentalista:
    - /fundamentalista: fundamentalista.md


theme:
  favicon: img/favicon.ico
  name: material
  logo: img/logo.png
  features:
    - content.code.copy
  language: pt-br
  palette:
    - scheme: default
      primary: white
      accent: brown
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: brown
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
