site_name: FOX - A LINK TO THE PRICE
site_description: Documentação para uso do robô para Telegram Fox - A Link to the Price
site_author: Samir Angelo Milani Martins
site_url: https://www.samirmartins.com.br

repo_name: samirmartins/fox_documentation
repo_url: https://github.com/samirmartins/fox_documentation

copyright: Copyright &copy; 2023 - Samir Martins

nav:
  - Principal: index.md

theme:
  favicon: img/favicon.ico
  name: material
  logo: img/logo.png
  features:
    - content.code.copy
  language: pt-br
  palette:
    - scheme: default
      primary: white
      accent: brown
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: brown
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
